server:
  port: 8080

spring:
  application:
    name: "refund-inquiry-service"
  datasource:
    url: jdbc:h2:mem:refund-inquiry;NON_KEYWORDS=USER
    driver-class-name: org.h2.Driver
    username: admin
    password: admin5678
  jpa:
    database: H2
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true
      path: /h2

secret :
  aes:
    secretKey: 3d1SkpT1suzids7W
  jwt:
    expiredMin: 30
    secret: 1fdebf47419f6dc98edebf9923
    issuer: szs


external:
  scrap-api-host: https://codetest-v4.3o3.co.kr
  api-key: aXC8zK6puHIf9l53L8TiQg==


springdoc:
  swagger-ui:
    path: /3o3/swagger.html